# Setup
title:        T Introduction
tagline:      T 는 차세대 데이터 공유 서비스입니다.
baseurl:      ""
paginate:     1
theme: jekyll-theme-cayman

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown