# Setup
title:        T 소개 페이지
tagline:      M 에서 진행되는 극비 프로젝트 중 하나인 T 를 공개합니다.
baseurl:      ""
paginate:     1
theme: jekyll-theme-cayman

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown